### ISSUE TITLE
Update rules_kotlin to 1.8.x

### ISSUE THREAD

**Issue by SanjayVas** [world-federation-of-advertisers/common-jvm#134]
We're currently using a pre-release version of rules_kotlin 1.6. There has now been an official release of 1.6.0: https://github.com/bazelbuild/rules_kotlin/releases/tag/v1.6.0

**Comment by SanjayVas** [comment]
RC3 was promoted to the official release, but we're still on RC2.

**Comment by SanjayVas** [comment]
Bumped to 1.8.x for support for Kotlin 1.8.

**Comment by riemanli** [comment]
rules_kotlin 1.8 is a pre-release in https://github.com/bazelbuild/rules_kotlin/releases. Is it ok to use? 

Note that if we want to use Kotlin 1.8, the pre-release version is required as it has the bug-fix to support Kotlin 1.8. See https://github.com/bazelbuild/rules_kotlin/issues/908.
