### ISSUE TITLE
TinkKeyId uses non-unique ID for blob key

### ISSUE THREAD

**Issue by SanjayVas** [world-federation-of-advertisers/common-jvm#138]
`TinkKeyId` uses the primary key ID from the keyset. Key IDs are apparently only unique within a given keyset, so this is not sufficiently unique for a blob key.

**Comment by tholenst** [comment]
Note that you can set the Key ID yourself now (in Java and C++).  See for example the test at https://github.com/tink-crypto/tink-java/blob/main/src/test/java/com/google/crypto/tink/KeysetHandleTest.java#L1213

**Comment by SanjayVas** [comment]
@renjiezh can this be closed? It looks like #236 resolves the issue.

**Comment by renjiezh** [comment]
This issue has been resolved by https://github.com/world-federation-of-advertisers/common-jvm/pull/236
