### ISSUE TITLE
Factor out WORKSPACE to bzl files

### ISSUE THREAD

**Issue by efoxepstein** [world-federation-of-advertisers/common-jvm#8]
See e.g. the structure in common-cpp: https://github.com/world-federation-of-advertisers/common-cpp/blob/main/build/deps.bzl

This makes it a lot more pleasant to include `common-jvm`, since it doesn't pollute the WORKSPACE with a ton of things that are hard to keep track of.

**Comment by SanjayVas** [comment]
See #20, #23, #27
